// words.js
const words = [
    { word: "之", definition: "갈 지" },
    { word: "不", definition: "아닐 부/불" },
    { word: "天", definition: "하늘 천" },
    { word: "語", definition: "말씀 어" },
    { word: "人", definition: "사람 인" },
    { word: "生", definition: "날 생" },
    { word: "的", definition: "과녁 적" },
    { word: "心", definition: "마음 심" },
    { word: "文", definition: "글월 문" },
    { word: "事", definition: "일 사" },
    { word: "山", definition: "뫼 산" },
    { word: "字", definition: "글자 자" },
    { word: "中", definition: "가운데 중" },
    { word: "一", definition: "한 일" },
    { word: "同", definition: "한가지 동" },
    { word: "學", definition: "배울 학" },
    { word: "三", definition: "석 삼" },
    { word: "明", definition: "밝을 명" },
    { word: "言", definition: "말씀 언" },
    { word: "大", definition: "큰 대" },
    { word: "敎", definition: "가르칠 교" },
    { word: "虛", definition: "빌 허" },
    { word: "而", definition: "말이을 이" },
    { word: "本", definition: "근본 본" },
    { word: "空", definition: "빌 공" },
    { word: "國", definition: "나라 국" },
    { word: "靑", definition: "푸를 청" },
    { word: "馬", definition: "말 마" },
    { word: "風", definition: "바람 풍" },
    { word: "樂", definition: "즐거울 낙" },
    { word: "子", definition: "아들 자" },
    { word: "論", definition: "논할 논 / 조리 윤" },
    { word: "異", definition: "다를 이" },
    { word: "實", definition: "열매 실" },
    { word: "說", definition: "말씀 설" },
    { word: "會", definition: "모일 회" },
    { word: "音", definition: "소리 음" },
    { word: "其", definition: "그 기" },
    { word: "理", definition: "다스릴 이" },
    { word: "傳", definition: "전할 전" },
    { word: "別", definition: "나눌 별" },
    { word: "世", definition: "인간(대) 세" },
    { word: "物", definition: "물건(만물) 물" },
    { word: "吾", definition: "나 오" },
    { word: "於", definition: "어조사 어" },
    { word: "與", definition: "더불 여" },
    { word: "雲", definition: "구름 운" },
    { word: "命", definition: "목숨 명" },
    { word: "家", definition: "집 가" },
    { word: "時", definition: "때 시" },
    { word: "上", definition: "위 상" },
    { word: "夫", definition: "사내 부" },
    { word: "主", definition: "주인 주" },
    { word: "間", definition: "사이 간" },
    { word: "道", definition: "길 도" },
    { word: "正", definition: "바를 정" },
];

export default words;
